### PR TITLE
add support for CONTRIBUTING.md file

### LINKED ISSUE #25: Support /CONTRIBUTING\.md/i file?
It is great place for describing a development flow and tasks.

### PR DESCRIPTION
**Pull request by tunnckoCore**
fixes #25

### CODE REVIEW

**Comment by olstenlarck** [comment]
damn... CircleCI is freakin instant, still surprising me. No matter what, i won't move from Github and CircleCI until someone beat them.

**Comment by zephraph** [comment]
Hmm... so what happens if there's a contributing file, but it *doesn't* have a maidfile comment... does it move on to the readme?

**Comment by olstenlarck** [comment]
Mmm.. not sure.

**Comment by egoist** [comment]
it doesn't 😅

**Comment by olstenlarck** [comment]
Probably ;d If we put it after the readme? Will it work that way or?

I'm more in flavor to PR for #4 which requires rethinking of those files and ideas - we should support only `maidfile.md` and optionally another files through the `--path` flag. I actually implemented it, but there are another problems for which i'll open new issue to discuss (related to passing flags to tasks which in some cases is pretty not comfortable).

**Pull request merged**
